name: ${name}
main: com.feildmaster.channelchat.Chat
version: ${version}
author: feildmaster
description: Simple channel chats.
dev-url: http://dev.bukkit.org/server-mods/channel-chat/

permissions:
  ChanChat.all:
    description: Gives all permissions to user
    children:
      ChanChat.admin: true
      ChanChat.create: true
      ChanChat.reload: true

  ChanChat.reload:
    description: 'Player can reload files'
  ChanChat.admin:
    description: 'Player can delete any channel'
  ChanChat.create:
    description: 'Player can create channels (bypasses allow-create-channels)'

commands:
  channel-admin:
    description: Admin Channels
    aliases:
      - chan
      - channel

  channel-chat:
    description: Base Commands
    aliases:
      - ch
      - cc
      - chat

  channel-join:
    description: Join Channels
    aliases:
      - join

  channel-create:
    description: Create Channels
    aliases:
      - create

  channel-delete:
    description: Delete Channels
    aliases:
      - delete

  channel-add:
    description: Add Players to Channel
    aliases:
      - add
      - invite

  channel-leave:
    description: Leave Channels
    aliases:
      - leave

  channel-set:
    descripton: Set Active Channel
    aliases:
      - set