name: ChannelChat
main: feildmaster.ChanChat.Chat
version: 0.1 beta
author: feildmaster
description: Simple channel chats.

permissions:
  ChanChat.all:
    description: Gives all permissions to user
    children:
      ChanChat.admin: true
      ChanChat.create: true
      ChanChat.reload: true

  ChanChat.reload:
    description: Player can reload files
    default: op

  ChanChat.admin:
    description: Player can delete any channel
    default: op

  ChanChat.create:
    description: Player can create channels
    default: true

commands:
  channel-admin:
    description: Admin Channels

  channel-chat:
    description: Base Commands
    aliases:
      - cc
      - chat

  channel-join:
    description: Join Channels
    aliases:
      - join

  channel-create:
    description: Create Channels
    aliases:
      - create

  channel-delete:
    description: Delete Channels
    aliases:
      - delete

  channel-add:
    description: Add Players to Channel
    aliases:
      - add
      - invite

  channel-leave:
    description: Leave Channels
    aliases:
      - leave

  channel-set:
    descripton: Set Active Channel
    aliases:
      - set